resolver: lts-18.20

packages:
  - .

extra-deps:
  - docopt-0.7.0.7
  - git: https://github.com/hpacheco/gloss-juicy
    commit: acbdfd864b7e574dfbe1595fbdcd154563b2a0ef
  - gloss-1.13.2.1
  - hsexif-0.6.1.8

flags:
  gloss:
    GLFW: true
    GLUT: false

allow-newer: true
