name: Haskell Stack CI

on: [push]

jobs:
  macos:
    strategy:
      matrix:
        os:
          - macos-10.15
          - macos-11.0
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Stack
        uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-no-global: true

      - name: Install Platypus
        run: brew install platypus

      - name: Install ImageMagick
        run: brew install imagemagick

      - name: Inject license keys
        run:
          sed -i ''
            's/licenses = \[\]/licenses = \[${{ secrets.LICENSE_KEYS }}\]/'
            source/Lib.hs

      - name: Build Perspec App
        run: make Perspec.app

      - name: Move App to Artifact Directory
        run: mkdir artifact && mv Perspec.app artifact

      - name: Upload MacOS Release
        uses: actions/upload-artifact@v2
        with:
          path: artifact
          name: perspec-app_${{ matrix.os }}_x86_64

  linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Stack
        uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-no-global: true

      - name: Install dependencies
        run:
          sudo apt install
            libgl1-mesa-dev
            libglu1-mesa-dev
            libxcursor-dev
            libxi-dev
            libxinerama-dev
            libxrandr-dev
            libxxf86vm-dev

      - name: Install Perspec CLI tool
        run: stack install

      - name: Upload Linux Release
        uses: actions/upload-artifact@v1
        with:
          path: /home/runner/.local/bin/perspec
          name: perspec_linux_x86_64.zip
